version: '3.7'
# This compose file is for building and running services "like in production" on dev machine.
# Note: for running existing versions of these services you only need to pull existing images.
services:
  prom-node-exporter:
    image: prom/node-exporter:v1.2.2
    container_name: prom-node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    ports:
      - 9100:9100

  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: prometheus
    user: root
    volumes:
      - ./monitoring/prometheus/data:/prometheus
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention=200h
    restart: always
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:8.2.1
    container_name: grafana
    restart: always
    ports:
      - 3000:3000

  loki:
    image: grafana/loki:main-cff8324
    container_name: loki
    restart: always
    volumes:
      - ./monitoring/loki/data:/data/loki
      - ./monitoring/loki/local-config.yaml:/etc/loki/local-config.yaml
    ports:
      - 3100:3100
    environment:
      - VIRTUAL_HOST=127.0.0.1
      - VIRTUAL_PORT=3100

  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    restart: unless-stopped
    ports: 
      - 8888:8080
    labels:
      org.label-schema.group: "monitoring"
